name: fluent_logger
description: fluent logger implementation for Dart
version: 0.1.0
author: ichigotake <k.wisiiy@gmail.com>
homepage: https://github.com/ichigotake/fluent-logger-dart
dev_dependencies:
  unittest: ">=0.10.1+2 <0.11.0"
